export const cards = [
    "I didn't want to do it",
    'Family pet ate it',
    'Left it at school over the weekend',
    "I don't know where it is",
    'I was gone when it was assigned',
    "I'm sick",
    'Blame the siblings',
    "Don't understand the assignment",
    'Night filled with extracurricular',
    "The WiFi wasn't working",
    'My Computer Broke',
    'My Mom Forgot It',
    'The Internet was Out',
    'My Grandma Died. Again',
    'The Older Kids Took it off me and Tore it Up',
    'My Mother wanted to Display it on the Fridge',
    'The Police Confiscated it as Evidence',
    'I was Abducted by Aliens and They took It',
    'I sent it to you in the Post',
    'My Dad mistook it for a Letter and Posted it to China',
    'I had to burn it in the Fireplace to keep myself Warm',
    'It flew out the Window of the Car',
    'I thought I’d do it Tomorrow because I’ll be Older and Wiser Then',
    'I did my Work. It’s all Up Here in my Head',
    'I didn’t do it because I didn’t want to add to your Workload',
];
